export type Category = "all" | "ui" | "motion" | "business";
export interface ComponentDoc {
  name: string;
  chinese: string;
  category: Exclude<Category, "all">;
  description: string;
  code: string;
  props: [string, string, string][];
}

export const categories = [
  { value: "all", label: "全部组件" },
  { value: "ui", label: "通用 UI" },
  { value: "motion", label: "视觉动效" },
  { value: "business", label: "业务组件" },
] as const;

export const catalog: ComponentDoc[] = [
  {
    name: "CompareSlider",
    chinese: "前后对比",
    category: "ui",
    description: "拖动一条分界线，在同一块画布里看见前后变化。",
    code: `import { CompareSlider } from '@ray-ui/react';\n\n<CompareSlider\n  before={<img src="/before.png" alt="原始稿" />}\n  after={<img src="/after.png" alt="完成稿" />}\n  beforeLabel="原始稿"\n  afterLabel="完成稿"\n  onValueChange={(value) => console.log(value)}\n/>`,
    props: [
      ["before / after", "ReactNode，两层内容会保持相同尺寸；图片建议使用 object-fit: cover", "必填"],
      ["value / defaultValue", "0–100 的受控 / 初始分界位置；非有限值按 50，越界会截断", "— / 50"],
      ["onValueChange", "(value: number) => void；拖动或键盘调整时调用", "—"],
      ["orientation", "horizontal 左右分界 | vertical 上下分界", "horizontal"],
      ["beforeLabel / afterLabel / label", "画布标签 / 滑块可访问名称；标签对读屏隐藏", "之前 / 之后 / 前后对比"],
      ["键盘与触控", "方向键每次 1，PageUp / PageDown 每次 10，Home / End 跳到边界；支持指针拖动", "—"],
      ["disabled / className / style / ref", "禁用交互 / 原生 div 属性；--ray-compare-position 可由组件内部维护，ref 指向容器", "false / —"],
    ],
  },
  {
    name: "FileDropzone",
    chinese: "文件投递区",
    category: "ui",
    description: "把文件拖进来，格式、大小和数量都在选择时即时校验。",
    code: `import { FileDropzone } from '@ray-ui/react';\n\n<FileDropzone\n  accept="image/*,.pdf"\n  maxFiles={3}\n  maxSize={5 * 1024 * 1024}\n  onValueChange={(files) => setFiles(files)}\n  onReject={(rejections) => console.log(rejections)}\n/>`,
    props: [
      ["value / defaultValue", "受控 / 初始 File[]；不传 value 时组件管理选择结果", "— / []"],
      ["onValueChange / onReject", "文件数组变化回调 / 被拒文件及 file-type、file-size、file-count、duplicate 原因", "—"],
      ["accept", "逗号分隔的扩展名、MIME 类型或通配 MIME，如 image/*,.pdf", "—"],
      ["multiple / maxFiles / maxSize", "允许多选 / 文件数量上限 / 单文件字节上限；超限文件不会进入 value", "true / 5 / 10 MB"],
      ["title / description / browseLabel", "投递区标题、说明和选择按钮文案", "把文件放在这里 / 自动说明 / 选择文件"],
      ["size / disabled", "sm | md / 禁用拖放、选择和移除", "md / false"],
      ["可访问性", "文件输入、状态播报、错误列表、焦点样式和键盘按钮；示例不会自动上传文件", "—"],
    ],
  },
  {
    name: "Timeline",
    chinese: "时间线",
    category: "business",
    description: "把项目进度、审核节点和发布步骤排成一条清晰的线。",
    code: `import { Timeline } from '@ray-ui/react';\n\n<Timeline items={[\n  { id: 'brief', title: '确认需求', time: '09:20', status: 'complete' },\n  { id: 'review', title: '等待评审', time: '现在', status: 'current', action: <button>查看详情</button> },\n  { id: 'ship', title: '发布版本', status: 'pending' },\n]} />`,
    props: [
      ["items", "TimelineItem[]；id 需要唯一，按数组顺序呈现；每项可带 title、description、time、dateTime、icon、action", "必填"],
      ["status", "complete 已完成 | current 进行中 | pending 待开始 | error 需要处理", "complete"],
      ["size / emptyMessage", "sm | md / items 为空时的说明", "md / 暂无动态"],
      ["statusLabels", "覆盖四种状态的可见文案，适合国际化或业务术语", "内置中文"],
      ["语义", "ol + li 保留顺序，current 节点带 aria-current=step，时间使用 time 元素", "—"],
      ["className / style / ref", "原生 ol 属性，ref 指向 HTMLOListElement", "—"],
    ],
  },
  {
    name: "SegmentedControl",
    chinese: "分段选择器",
    category: "ui",
    description: "在同一组互斥视图之间快速切换，保留明确的键盘焦点。",
    code: `import { SegmentedControl } from '@ray-ui/react';\n\n<SegmentedControl\n  aria-label="工作台视图"\n  options={[\n    { value: 'overview', label: '概览' },\n    { value: 'activity', label: '活动' },\n    { value: 'settings', label: '设置' },\n  ]}\n  defaultValue="overview"\n  onValueChange={(value) => setView(value)}\n/>`,
    props: [
      ["options", "{ value, label, disabled? }[]；至少提供一个可用选项，value 需要唯一", "必填"],
      ["value / defaultValue", "受控值 / 初始值；没有可用初始值时自动选择第一个未禁用选项", "— / 首个可用"],
      ["onValueChange", "(value: string) => void；点击或方向键切换时调用", "—"],
      ["size / fullWidth", "sm | md | lg / 是否让选项平分容器宽度", "md / false"],
      ["disabled / name", "禁用整组 / data-name 标识；单项可在 options 中单独禁用", "false / —"],
      ["键盘与语义", "radiogroup + radio；← → / ↑ ↓ 循环切换，Home / End 跳到首尾，Tab 只进入当前选项", "—"],
    ],
  },
  {
    name: "ProgressRing",
    chinese: "进度环",
    category: "motion",
    description: "用一圈轻量的轨迹表达上传、同步或后台任务的完成度。",
    code: `import { ProgressRing } from '@ray-ui/react';\n\n<ProgressRing value={68} label="上传进度" />\n<ProgressRing value={42} max={60} tone="success" size="sm" />\n<ProgressRing value={null} label="分析中" tone="warning" />`,
    props: [
      ["value / max", "当前值 / 上限；value={null} 显示不确定进度，非有限值按 0，数值会限制在 0–max", "0 / 100"],
      ["size / strokeWidth", "sm 52px | md 96px | lg 148px | number 24–512px / SVG 轨迹宽度", "md / 8"],
      ["label / showValue", "进度环的可访问名称 / 是否显示中心文本", "进度 / true"],
      ["formatValue", "(value, max) => string，自定义中心文本格式", "百分比"],
      ["tone", "accent | success | warning | danger", "accent"],
      ["语义与动效", "role=progressbar；确定进度提供 aria-valuenow，不确定进度遵循减少动态效果设置", "—"],
    ],
  },
  {
    name: "EmptyState",
    chinese: "空状态面板",
    category: "ui",
    description: "给没有内容的页面一个清晰的下一步，也让空白保留呼吸感。",
    code: `import { EmptyState, Button } from '@ray-ui/react';\n\n<EmptyState\n  title="没有匹配的灵感"\n  description="换个关键词试试，或者清除筛选条件。"\n  action={<Button>清除筛选</Button>}\n/>`,
    props: [
      ["title", "ReactNode，作为面板标题并关联区域语义", "必填"],
      ["description / icon / action", "补充说明 / 装饰图标（对读屏隐藏）/ 下一步操作节点", "—"],
      ["size / tone", "sm | md / neutral | accent", "md / neutral"],
      ["className / style / ref", "原生 div 属性与 ref；适合放在列表、搜索结果或工作台面板中", "—"],
    ],
  },
  {
    name: "NotificationHotspot",
    chinese: "通知热点",
    category: "ui",
    description: "一枚轻轻呼吸的提醒，让新消息恰好被看见。",
    code: `import { NotificationHotspot, Button } from '@ray-ui/react';\nimport '@ray-ui/react/styles.css';\n\n<NotificationHotspot count={8} pulse>\n  <Button>消息</Button>\n</NotificationHotspot>\n\n<NotificationHotspot label="有新通知" />\n<NotificationHotspot count={128} max={99} tone="info" />`,
    props: [
      ["children", "ReactNode，包裹按钮、图标或头像；省略时独立显示", "—"],
      ["count / max", "未读数 / 显示上限，超出显示 99+；count 省略为红点；负数、非有限数按 0，小数向下取整；max 至少 1，非有限数按 99", "— / 99"],
      ["active / showZero", "是否显示热点 / 是否显示零值", "true / false"],
      ["pulse", "轻微扩散动画，遵循系统减少动态效果设置", "false"],
      ["tone", "danger | warning | info | success", "danger"],
      ["placement", "top-right | top-left | bottom-right | bottom-left", "top-right"],
      ["label / announce", "读屏通知文字（默认完整数量）/ 使用 status 动态播报", "自动生成 / false"],
      ["className / style / ref", "原生 span 属性；--ray-hotspot-color 覆盖颜色；热点不拦截点击，子控件需自行提供可访问名称，外层应留出溢出空间", "—"],
    ],
  },
  {
    name: "ArtText",
    chinese: "艺术字",
    category: "motion",
    description: "手作线条动画：独立笔画、轻重收锋与逐笔成字，支持进度时间轴。",
    code: `import { StrokeLettering, growthLettering } from '@ray-ui/react';\nimport '@ray-ui/react/styles.css';\n\n// 将 progress 从 0 推进到 1，逐笔绘制「生长」。\n<StrokeLettering artwork={growthLettering} progress={0.65} color="#343c36" />\n\n// artwork 接受自定义 SVG 笔画，不依赖字体文件。\n// 原有字体材质仍使用 ArtText 组件。`,
    props: [
      ["StrokeLettering.artwork", "{ label, viewBox, strokes }；笔画含 path 中心线、可选 outline 压感轮廓、width 揭示宽度、duration 相对时长；growthLettering 为手绘「生长」字稿", "必填"],
      ["StrokeLettering.progress / color", "0–1 绘制进度 / 笔触颜色；进度由外部时间轴驱动，组件不自动播放；非有限进度按完成处理", "1 / currentColor"],
      ["StrokeLettering SVG 属性", "支持 className、style、ref 与 aria-label；默认以 artwork.label 提供可访问名称；以下为保留的 ArtText API", "—"],
      ["children", "string，保留原始文字与换行；长文字自动换行，可选择、复制与读屏", "必填"],
      ["variant", "moon-silver 月白银 | radiant-alloy 幻金流焰 | ink-relief 墨版长影 | sugar-echo 像素糖影", "moon-silver"],
      ["fontSize / letterSpacing", "number（px）| CSS 长度字符串；支持 clamp() 与 em", "继承字号 / 各字效默认字距"],
      ["color / secondaryColor", "CSS 颜色；月白银为银面亮色与暗部，其余字效用于折光、阴影或轮廓", "各字效默认配色"],
      ["animated", "boolean，moon-silver 与 radiant-alloy 支持柔光移动；遵循系统减少动态效果", "false"],
      ["className / style / ref", "原生 span 属性；style 优先，可覆盖字体、字重和 CSS 变量 --ray-art-color / --ray-art-secondary", "—"],
      ["语义与背景", "真实 span 文字，标题请包在 h1 / h2 中；装饰层对读屏隐藏且不可选中；月白银与幻金流焰建议深色背景；月白银使用本机 Noto Serif SC 600 字重并有宋体回退", "—"],
    ],
  },
  {
    name: "Pagination",
    chinese: "分页",
    category: "ui",
    description: "一页页翻阅，让更多内容有序展开。",
    code: `import { useState } from 'react';\nimport { Pagination } from '@ray-ui/react';\n\nexport function Notes({ items }: { items: { id: string; title: string }[] }) {\n  const [page, setPage] = useState(1);\n  const [pageSize, setPageSize] = useState(10);\n  const current = Math.min(page, Math.max(1, Math.ceil(items.length / pageSize)));\n  return <>\n    {items.slice((current - 1) * pageSize, current * pageSize).map(item =>\n      <p key={item.id}>{item.title}</p>)}\n    <Pagination total={items.length} page={current} pageSize={pageSize}\n      onPageChange={(next, size) => { setPage(next); setPageSize(size); }}\n      showTotal showSizeChanger showQuickJumper />\n  </>;\n}\n\n// 自动管理页码，也可以只显示紧凑分页。\n<Pagination total={96} defaultPage={4} />\n<Pagination total={96} variant="compact" size="sm" />`,
    props: [
      ["total", "number，总记录数；负数 / 非有限值按 0，小数向下取整", "必填"],
      ["page / defaultPage", "number，受控 / 初始页码，从 1 开始；超出总页数时限制到末页", "— / 1"],
      ["pageSize / defaultPageSize", "number，受控 / 初始每页条数；最小为 1，非有限值按 10", "— / 10"],
      ["onPageChange", "(page: number, pageSize: number) => void；点击当前页不触发，修改每页条数时请求第 1 页", "—"],
      ["showSizeChanger / pageSizeOptions / onPageSizeChange", "显示自定义选择器 / 可选正整数条数 / (size: number) => void；当前条数自动加入选项", "false / [10,20,50,100] / —"],
      ["showTotal / showQuickJumper", "显示当前记录范围与总数 / 显示跳页输入框，Enter 或点击跳转确认", "false / false"],
      ["variant / size / disabled", "default 页码 | compact 简洁 / sm | md / 禁用所有分页交互", "default / md / false"],
      ["边界与数据变化", "0 条时显示 0 / 0 并禁用翻页；外部 total / pageSize 变化只规范显示值，不自动发回调或请求数据", "—"],
      ["aria-label / className / style / ref", "原生 nav 属性；--ray-pagination-button-size 可调尺寸；容器不超过 420px 自动显示紧凑模式", "分页导航 / —"],
      ["键盘与内容", "Tab、Enter、Space；当前页带 aria-current，切页播报；组件负责分页控件，数据加载、切片、滚动与焦点由应用处理", "—"],
    ],
  },
  {
    name: "HomeButton",
    chinese: "回到首页",
    category: "ui",
    description: "无论走多远，一键回到熟悉的起点。",
    code: `import { HomeButton } from '@ray-ui/react';\n\n<HomeButton href="/" />\n<HomeButton href="/workspace" variant="solid" label="返回工作台" />\n<HomeButton href="/" iconOnly position="bottom-left" />\n\n// 单页应用：navigate 由你的路由提供。\n<HomeButton href="/" onNavigate={(href) => navigate(href)} />\n\n// 异步路由的加载状态由调用方控制。\n<HomeButton href="/" loading loadingLabel="正在返回" />`,
    props: [
      ["href", "string，首页 URL；部署在子路径时传入实际首页，如 /app/", "/"],
      ["label / loadingLabel", "string，正常 / 加载时的文字与默认可访问名称", "回到首页 / 正在返回"],
      ["variant", "surface 浅底胶囊 | solid 强调色 | ghost 轻量文字", "surface"],
      ["size / iconOnly", "sm（36px）| md（46px）| lg（54px）/ 仅显示小屋图标", "md / false"],
      ["position", "inline | bottom-left | bottom-right，悬浮时为 fixed 定位", "inline"],
      ["onNavigate", "(href: string) => void，仅接管普通同页点击；Ctrl / Cmd / Shift / Alt、辅助点击、新窗口和下载保留原生链接行为", "—"],
      ["disabled / loading", "boolean，禁止跳转并移出 Tab 顺序；加载时显示转圈与 aria-busy，不自动管理异步操作", "false / false"],
      ["onClick / target / rel / download", "原生链接属性；onClick 可 preventDefault 取消；_blank 自动补 noopener", "—"],
      ["aria-label / title / className / style / ref", "原生 a 属性；ref 指向 HTMLAnchorElement；长文字空间不足时省略", "随 label / —"],
      ["键盘与样式", "Tab 聚焦、Enter 跳转；尊重减少动态效果；--ray-home-offset / --ray-home-z-index 调整悬浮边距与层级", "24px / 40"],
    ],
  },
  {
    name: "PageNavigation",
    chinese: "前进后退与回顶",
    category: "ui",
    description: "前进一步，回看一页，轻轻回到顶部。",
    code: `import { useState } from 'react';\nimport { PageNavigation } from '@ray-ui/react';\n\n// 页面悬浮；前进 / 后退默认调用浏览器历史。\n<PageNavigation position="bottom-right" orientation="vertical" />\n\n// 独立滚动容器；使用状态回调 ref 追踪容器的挂载与更换。\nexport function Reader() {\n  const [target, setTarget] = useState<HTMLDivElement | null>(null);\n  return <>\n    <div ref={setTarget} style={{ height: 320, overflowY: 'auto' }}\n      tabIndex={0} role="region" aria-label="阅读内容">\n      <article style={{ minHeight: 900 }}>你的长篇内容</article>\n    </div>\n    <PageNavigation scrollTarget={target} showLabels />\n  </>;\n}`,
    props: [
      ["onBack / onForward", "鼠标事件回调，替代浏览器历史；可接入路由或分步流程", "history.back() / forward()"],
      ["canGoBack / canGoForward / disabled", "前后按钮可用状态 / 全部禁用；历史边界由应用传入，不从 history.length 推断", "true / true / false"],
      ["scrollTarget", "HTMLElement | null；省略滚动窗口，null 等待容器挂载，支持运行时更换", "window"],
      ["onBackToTop / behavior", "滚动前回调，可 preventDefault 取消 / smooth | instant | auto", "— / smooth"],
      ["topThreshold", "number，距离顶部不超过该像素时禁用回顶；负数按 0，非有限值按 32", "32"],
      ["orientation / position", "horizontal | vertical / inline | bottom-right | bottom-left；悬浮时为 fixed 定位", "horizontal / inline"],
      ["size / showLabels / showProgress", "sm（36px 按钮）| md（44px 按钮）/ 显示文字 / 显示真实滚动进度环", "md / false / true"],
      ["backLabel / forwardLabel / topLabel", "可访问名称与悬停提示；showLabels 开启时也作为可见文字", "后退 / 前进 / 回到顶部"],
      ["aria-label / className / style / ref", "原生 div 属性；CSS 变量 --ray-navigation-offset 调整悬浮边距，--ray-navigation-z-index 调整层级", "页面导航 / —"],
      ["键盘与动效", "Tab 按后退、前进、回顶顺序聚焦可用按钮；Enter / Space 激活；减少动态效果时即时回顶", "—"],
    ],
  },
  {
    name: "FlameGraph",
    chinese: "火焰图",
    category: "business",
    description: "沿着调用栈，找到时间花在哪里。",
    code: `import { FlameGraph } from '@ray-ui/react';\n\n<FlameGraph data={[{\n  id: 'app', name: 'app.bootstrap()', value: 1000,\n  children: [\n    { id: 'fetch', name: 'fetchData()', value: 650, children: [\n      { id: 'parse', name: 'JSON.parse()', value: 240 },\n    ] },\n    { id: 'render', name: 'render()', value: 280 },\n  ],\n}]} />`,
    props: [
      ["data", "FlameGraphNode[]：全树唯一 id、name、可选 value 和 children；value 为包含子调用的耗时", "必填"],
      ["value / defaultValue", "string | null，受控 / 初始下钻节点 id；null 查看全部", "— / null"],
      ["onValueChange", "(id: string | null) => void，点击下钻、返回或重置后通知", "—"],
      ["title / formatValue", "标题 / 数值格式函数；所有节点使用相同单位", "调用栈火焰图 / N ms"],
      ["showSearch / showDetails", "显示函数名称搜索 / 悬停或聚焦的调用详情", "true / true"],
      ["emptyMessage", "空数据或全零数据文案；重复 id 等无效结构显示具体说明", "暂无调用数据"],
      ["数据规则", "缺失 / 负数 / 非有限值按 0 处理；父值不足时提升到子调用总和；不修改输入", "最多 100 层 / 5000 节点"],
      ["交互 / className / style", "← → 同层，↑ 子调用，↓ 父调用，Enter / Space 下钻，Esc 返回；CSS 变量可调行高", "—"],
    ],
  },
  {
    name: "Heatmap",
    chinese: "热力图",
    category: "business",
    description: "把日常积累，铺成一幅有温度的日历。",
    code: `import { Heatmap } from '@ray-ui/react';\n\n<Heatmap\n  startDate="2026-06-15" endDate="2026-09-12"\n  data={[\n    { date: '2026-09-10', value: 4 },\n    { date: '2026-09-11', value: 9 },\n    { date: '2026-09-12', value: 6 },\n  ]}\n  tone="green"\n  formatValue={(value) => value + ' 次贡献'}\n  onValueChange={(date, day) => console.log(date, day.value)}\n/>`,
    props: [
      ["data", "HeatmapDatum[]：date 为 YYYY-MM-DD，value 为非负数；缺失日补 0，同日最后一条生效", "必填"],
      ["startDate / endDate", "YYYY-MM-DD，包含首尾，1–366 天；无效范围显示说明", "必填"],
      ["title / tone", "标题 / green | orange | blue | purple", "活动热力图 / green"],
      ["value / defaultValue", "string | null，受控 / 初始选中日期；null 清除选择", "— / null"],
      ["onValueChange", "(date: string, day: HeatmapDatum) => void，点击或回车 / 空格选日", "—"],
      ["weekStartsOn", "0 周日 | 1 周一", "1"],
      ["maxValue", "正数色阶上限；超过上限显示最深色，不改变数值", "范围内最大值"],
      ["formatValue / showLegend / emptyMessage", "数值格式函数 / 显示图例 / 全零数据文案", "N 次活动 / true / 暂无活动记录"],
      ["键盘 / style / className", "单一 Tab 入口；方向键、Home / End、Ctrl + Home / End；CSS 变量可调格子尺寸与间距", "—"],
    ],
  },
  {
    name: "AIOrb",
    chinese: "AI 对话球",
    category: "motion",
    description: "一束会倾听的光，让对话有了温度。",
    code: `import { AIOrb } from '@ray-ui/react';\n\n<AIOrb state="idle" size="lg" />\n<AIOrb state="listening" audioLevel={0.45} />\n<AIOrb state="thinking" />\n<AIOrb state="speaking" audioLevel={0.8} label="正在为你解答" />`,
    props: [
      ["state", "idle 待机 | listening 聆听 | thinking 思考 | speaking 回应 | error 连接中断", "idle"],
      ["audioLevel", "number，0–1 音量；仅聆听和回应时影响脉动，组件不采集音频", "0"],
      ["size", "sm (64) | md (144) | lg (256) | number (32–512)，包含柔光的画布尺寸 px", "md"],
      ["paused", "boolean，冻结当前动画，再次播放从原处继续", "false"],
      ["label / hideLabel", "自定义状态文字 / 仅视觉隐藏文字，保留读屏播报", "随 state 变化 / false"],
      ["className / style / ref", "原生 span 属性；内置减少动态效果、离屏和后台暂停，WebGL 不可用时静态降级", "—"],
    ],
  },
  {
    name: "Carousel",
    chinese: "轮播图",
    category: "ui",
    description: "风景与故事，一张张慢慢展开。",
    code: `import { Carousel } from '@ray-ui/react';\n\n<Carousel aria-label="旅行相册" items={[\n  { id: 'mountain', label: '山间清晨', content: <img src="/mountain.jpg" alt="晨光中的山峦" /> },\n  { id: 'sea', label: '海边日落', content: <img src="/sea.jpg" alt="夕阳下的海岸" /> },\n]} />`,
    props: [
      ["items", "CarouselItem[]：唯一 id、可访问 label、content（图片或自定义内容）", "必填"],
      ["value / defaultValue", "number，受控 / 初始索引，从 0 开始，越界时限制到有效范围", "— / 0"],
      ["onValueChange", "(index: number) => void", "—"],
      ["loop", "boolean，首尾循环；关闭后边界按钮禁用", "true"],
      ["autoPlay / interval", "boolean / number，自动播放及毫秒间隔（最小 1000）", "false / 5000"],
      ["aria-label / className / style", "区域名称 / 自定义样式", "轮播图 / — / —"],
      ["交互", "聚焦区域使用 ← → / Home / End；支持滑动，悬停或焦点在内部时暂停，减少动态效果时禁止自动播放", "—"],
    ],
  },
  {
    name: "BreathingIndicator",
    chinese: "呼吸指示器",
    category: "motion",
    description: "浮光、游环、潮息，让状态自然流动。",
    code: `import { BreathingIndicator } from '@ray-ui/react';\n\n<BreathingIndicator variant="glow" label="系统运行中" />\n<BreathingIndicator variant="orbit" label="正在同步" />\n<BreathingIndicator variant="wave" label="后台处理中" />`,
    props: [
      ["label / hideLabel", "string / boolean，状态文本 / 仅视觉隐藏文字，保留无障碍文本", "运行中 / false"],
      ["variant", "glow 浮光 | orbit 游环 | wave 潮息", "glow"],
      ["status", "normal 正常 | degraded 部分出错（琥珀色、变速） | failed 完全瘫痪（红色、静止）", "normal"],
      ["description", "string，可选说明文字", "—"],
      ["tone", "green | blue | orange | purple", "green"],
      ["size", "sm | md | lg", "md"],
      ["duration", "number，基础节奏毫秒，各层错速运动；最小 1600", "6000"],
      ["paused", "boolean，冻结当前动画，恢复时继续；不改变 label", "false"],
      ["className / style / ref", "原生 span 属性；尊重系统减少动态效果偏好", "—"],
    ],
  },
  {
    name: "DownloadButton",
    chinese: "下载按钮",
    category: "ui",
    description: "轻轻一点，把需要的文件带走。",
    code: `import { DownloadButton } from '@ray-ui/react';\n\n<DownloadButton filename="notes.txt" data="我的灵感笔记">\n  下载文件\n</DownloadButton>\n\n<DownloadButton filename="guide.pdf" href="/files/guide.pdf">\n  下载指南\n</DownloadButton>`,
    props: [
      ["filename", "string，建议保存的文件名", "必填"],
      ["data / href", "string | Blob 文件内容 / 文件 URL，二选一；跨域 URL 是否下载取决于服务端响应", "必填"],
      ["mimeType", "string，仅用于字符串 data", "text/plain;charset=utf-8"],
      ["icon / children", "ReactNode，图标 / 按钮文案", "— / 下载文件"],
      ["onDownload / onError", "请求下载后回调（不代表保存完成） / 错误回调", "—"],
      ["variant / size / disabled / loading / ref", "继承 Button 属性；onClick 可 preventDefault 取消下载", "同 Button"],
    ],
  },
  {
    name: "Leaderboard",
    chinese: "排行榜",
    category: "business",
    description: "四色进度条，让名次与成绩差距一眼清晰。",
    code: `import { Leaderboard } from '@ray-ui/react';\n\n<Leaderboard items={[\n  { id: 'lin', name: '林予安', value: 12860, tone: 'orange', change: 3 },\n  { id: 'chen', name: '陈墨', value: 11420, tone: 'blue', change: 1 },\n  { id: 'xu', name: '许知远', value: 10980, tone: 'purple', change: -1 },\n  { id: 'zhou', name: '周可', value: 9640, tone: 'teal', change: 0 },\n]} />`,
    props: [
      ["items", "LeaderboardItem[]，唯一 id、name、value；按分数降序展示", "必填"],
      ["items[].avatar / tone", "头像 URL / orange | blue | purple | teal", "姓名首字 / 按输入顺序轮换"],
      ["items[].change", "排名变化：正数上升、负数下降、0 持平", "0"],
      ["title / valueLabel", "标题 / 分数的可访问单位", "积分排行榜 / 积分"],
      ["formatValue", "(value: number) => string", "中文千位分隔"],
      ["renderChange", "(change: number) => ReactNode，自定义变化图标", "升 / 降 / 持平文字"],
      ["emptyMessage", "空状态文案", "暂无排行数据"],
      ["className / style", "外层 section 样式；百分比相对榜首，同分保持输入顺序", "—"],
    ],
  },
  {
    name: "ScrollArea",
    chinese: "滚动条",
    category: "ui",
    description: "细细一条，让长内容自在向下延伸。",
    code: `import { ScrollArea } from '@ray-ui/react';\n\n<ScrollArea aria-label="内容列表" style={{ height: 300 }}>\n  {/* 放入超过容器高度的内容，即可滚动 */}\n</ScrollArea>\n\n// 页面或已有滚动容器也可直接添加 className="ray-scrollbar"。`,
    props: [
      ["aria-label", "string，滚动区域的可访问名称", "必填"],
      ["children", "ReactNode，滚动内容", "—"],
      ["style / className", "容器样式，可设置 height / maxHeight", "max-height: 320px"],
      ["tabIndex / ref", "原生 div 属性；聚焦后支持键盘滚动", "0 / —"],
    ],
  },
  {
    name: "Slider",
    chinese: "滑动条",
    category: "ui",
    description: "轻轻滑动，把数值调到刚刚好。",
    code: `import { useState } from 'react';\nimport { Slider } from '@ray-ui/react';\n\nexport function Volume() {\n  const [value, setValue] = useState(64);\n  return <Slider label="播放音量" value={value}\n    onValueChange={setValue}\n    formatValue={(value) => value + '%'} />;\n}`,
    props: [
      ["label / value", "string / number，标签与受控数值", "必填"],
      ["onValueChange", "(value: number) => void", "—"],
      ["min / max / step", "number，范围与步长；value 应对齐步长", "0 / 100 / 1"],
      ["formatValue", "(value: number) => string，数值显示格式", "String"],
      ["disabled / name / ref", "原生 input 属性", "—"],
      ["className / style", "外层容器样式", "—"],
    ],
  },
  {
    name: "Button",
    chinese: "按钮",
    category: "ui",
    description: "每一次行动，都从一个清晰的按钮开始。",
    code: `import { Button } from '@ray-ui/react';\n\n<Button onClick={() => alert('开始构建！')}>\n  开始构建\n</Button>\n<Button variant="outline">了解更多</Button>\n<Button loading>正在保存</Button>`,
    props: [
      ["variant", "primary | secondary | outline | ghost | danger", "primary"],
      ["size", "sm | md | lg", "md"],
      ["loading", "boolean", "false"],
      ["disabled / onClick / ref", "原生 button 属性", "—"],
    ],
  },
  {
    name: "Input",
    chinese: "输入框",
    category: "ui",
    description: "标签、提示、校验反馈，照顾每一个输入。",
    code: `import { Input } from '@ray-ui/react';\n\n<Input label="邮箱地址" type="email"\n  placeholder="you@example.com"\n  hint="我们会好好保管你的邮箱。" />\n<Input label="项目名称" error="请填写项目名称" />`,
    props: [
      ["label", "string", "—"],
      ["hint / error", "string", "—"],
      ["value / onChange / ref", "原生 input 属性", "—"],
    ],
  },
  {
    name: "DatePicker",
    chinese: "日期选择器",
    category: "ui",
    description: "给下一次出发，选一个刚刚好的日子。",
    code: `import { useState } from 'react';\nimport { DatePicker } from '@ray-ui/react';\n\nexport function ProjectDate() {\n  const [date, setDate] = useState<Date | undefined>();\n  return (\n    <DatePicker\n      label="项目启动日期"\n      name="startDate"\n      value={date}\n      onValueChange={setDate}\n      minDate={new Date(2026, 8, 1)}\n      maxDate={new Date(2026, 11, 31)}\n      hint="请选择 2026 年 9–12 月的日期。"\n    />\n  );\n}`,
    props: [
      ["value / defaultValue", "Date | undefined，受控值 / 非受控初值", "—"],
      ["onValueChange", "(date: Date | undefined) => void，清除时传 undefined", "—"],
      ["minDate / maxDate", "Date，按本地日限制，含边界、忽略时分秒", "—"],
      ["label / placeholder", "string，标签 / 未选择时的提示", "— / 选择日期"],
      ["hint / error", "string，提示或错误信息", "—"],
      ["clearable / disabled", "boolean，允许清除 / 禁用整个控件", "true / false"],
      ["name", "string，表单提交为本地 YYYY-MM-DD", "—"],
      ["id / className / ref", "string / string / Ref<HTMLButtonElement>", "—"],
    ],
  },
  {
    name: "Switch",
    chinese: "开关",
    category: "ui",
    description: "一个小小的切换，让偏好即刻生效。",
    code: `import { useState } from 'react';\nimport { Switch } from '@ray-ui/react';\n\nexport function Preferences() {\n  const [enabled, setEnabled] = useState(true);\n  return <Switch label="接收更新通知"\n    checked={enabled} onCheckedChange={setEnabled} />;\n}`,
    props: [
      ["checked / defaultChecked", "boolean", "false"],
      ["onCheckedChange", "(checked: boolean) => void", "—"],
      ["label / disabled / name", "标签与原生 input 属性", "—"],
    ],
  },
  {
    name: "SpotlightCard",
    chinese: "聚光卡片",
    category: "motion",
    description: "光随指尖而动，为内容添一点灵感。",
    code: `import { SpotlightCard } from '@ray-ui/react';\n\n<SpotlightCard style={{ padding: 32 }}>\n  <h3>让灵感发光。</h3>\n  <p>移动指针，探索属于你的光。</p>\n</SpotlightCard>`,
    props: [
      ["children", "ReactNode", "—"],
      ["className / style / ref", "原生 div 属性", "—"],
    ],
  },
  {
    name: "Badge",
    chinese: "徽标",
    category: "ui",
    description: "轻巧的状态表达，让信息一目了然。",
    code: `import { Badge } from '@ray-ui/react';\n\n<Badge variant="success">已完成</Badge>\n<Badge variant="warning">进行中</Badge>\n<Badge variant="info">新功能</Badge>`,
    props: [
      ["variant", "neutral | success | warning | danger | info", "neutral"],
      ["children / className / ref", "原生 span 属性", "—"],
    ],
  },
  {
    name: "AnimatedNumber",
    chinese: "数字动画",
    category: "motion",
    description: "让每一份增长，都有恰到好处的仪式感。",
    code: `import { useState } from 'react';\nimport { AnimatedNumber, Button } from '@ray-ui/react';\n\nexport function Counter() {\n  const [value, setValue] = useState(1280);\n  return <>\n    <AnimatedNumber value={value} prefix="¥" duration={900} />\n    <Button onClick={() => setValue(value + 100)}>增加</Button>\n  </>;\n}`,
    props: [
      ["value", "number", "必填"],
      ["duration", "number，单位 ms", "900"],
      ["prefix / suffix / className", "string", "—"],
    ],
  },
  {
    name: "Tabs",
    chinese: "标签页",
    category: "ui",
    description: "切换视角，让相关内容井然有序。",
    code: `import { Tabs } from '@ray-ui/react';\n\n<Tabs aria-label="项目视图" items={[\n  { value: 'overview', label: '概览', content: <p>项目概览</p> },\n  { value: 'activity', label: '动态', content: <p>最近动态</p> },\n]} />`,
    props: [
      ["items", "{ value, label, content, disabled? }[]", "必填"],
      ["value / defaultValue", "string", "首个可用项"],
      ["onValueChange", "(value: string) => void", "—"],
    ],
  },
  {
    name: "Dialog",
    chinese: "对话框",
    category: "ui",
    description: "留一点专注空间，完成重要的事情。",
    code: `import { Dialog, Button, Input } from '@ray-ui/react';\n\n<Dialog trigger={<Button>创建项目</Button>}\n  title="创建新项目" description="给你的下一个想法起个名字。">\n  <Input label="项目名称" placeholder="我的新项目" />\n</Dialog>`,
    props: [
      ["trigger", "可接收 ref 与事件的元素，或文本", "必填"],
      ["title / description", "string", "标题必填"],
      ["open / onOpenChange", "boolean / (open: boolean) => void", "非受控"],
      ["children / className", "ReactNode / string", "—"],
    ],
  },
  {
    name: "StackedDrawer",
    chinese: "堆叠卡片抽屉",
    category: "ui",
    description: "新内容层层展开，来时的线索始终都在。",
    code: `import { StackedDrawer, Button, Input } from '@ray-ui/react';\n\n<StackedDrawer\n  trigger={<Button>打开项目</Button>}\n  title="项目概览" description="从一个小小的想法开始。"\n>\n  <Input label="项目名称" defaultValue="下一个好点子" />\n  <StackedDrawer\n    trigger={<Button>设计细节</Button>}\n    title="设计细节" description="上一张卡片会缩小后退。"\n  >\n    <p>关闭当前层后，上一层的输入依然保留。</p>\n    <StackedDrawer trigger={<Button>准备清单</Button>} title="准备清单">\n      <p>一切就绪，可以出发。</p>\n    </StackedDrawer>\n  </StackedDrawer>\n</StackedDrawer>`,
    props: [
      ["trigger", "可接收 ref 与事件的元素，或文本", "必填"],
      ["title / description", "string，当前卡片的标题与说明", "标题必填"],
      ["children", "ReactNode，可嵌套 StackedDrawer 形成多层卡片", "必填"],
      ["footer", "ReactNode，固定在底部的操作区", "—"],
      ["open / onOpenChange", "boolean / (open: boolean) => void", "非受控"],
      ["defaultOpen", "boolean，非受控模式下的初始状态", "false"],
      ["className", "string，卡片容器的自定义类名", "—"],
    ],
  },
  {
    name: "DataTable",
    chinese: "数据表格",
    category: "business",
    description: "搜索、排序与分页，把复杂数据变清晰。",
    code: `import { DataTable } from '@ray-ui/react';\n\nconst data = [\n  { id: '1', name: '设计系统', status: '进行中' },\n  { id: '2', name: '个人主页', status: '已完成' },\n];\n\n<DataTable data={data} caption="我的项目" pageSize={5}\n  columns={[\n    { key: 'name', header: '项目', sortable: true },\n    { key: 'status', header: '状态' },\n  ]} />`,
    props: [
      ["data", "T[]，每行必须有唯一 id: string", "必填"],
      ["columns", "{ key, header, sortable?, render? }[]", "必填"],
      ["pageSize", "number", "5"],
      ["caption / searchPlaceholder", "string", "数据列表 / 搜索数据…"],
    ],
  },
  {
    name: "StackedCards",
    chinese: "堆叠卡片列表",
    category: "ui",
    description: "把列表叠成一组卡片，点开一项，轻轻收好其余。",
    code: `import { StackedCards } from '@ray-ui/react';\n\n<StackedCards\n  aria-label="我的计划"\n  defaultValue="weekend"\n  items={[\n    { id: 'design', title: '品牌视觉探索', tone: 'sage',\n      meta: '09.10', content: <p>收集配色和字形灵感。</p> },\n    { id: 'room', title: '个人空间改造', tone: 'sand',\n      meta: '09.11', content: <p>一盏灯、一盆绿植。</p> },\n    { id: 'weekend', title: '周末漫游计划', tone: 'clay',\n      meta: '09.12', content: <p>带上相机，去收集一点日常之外。</p> },\n  ]}\n/>`,
    props: [
      ["items", "StackedCardItem[]，每项提供唯一 id、title、content", "必填"],
      ["items[].tone", "neutral | sage | sand | clay，卡片底色", "neutral"],
      ["items[].icon / meta", "ReactNode，标题图标 / 辅助信息，避免交互元素", "序号 / —"],
      ["value / defaultValue", "string | null，展开项 id；null 收起全部", "首项"],
      ["onValueChange", "(id: string | null) => void", "—"],
      ["className / aria-label", "自定义类名 / 列表的可访问名称", "— / 堆叠卡片列表"],
    ],
  },
  {
    name: "Card",
    chinese: "卡片",
    category: "ui",
    description: "给每一组内容，一个舒服的容器。",
    code: `import { Card, Badge } from '@ray-ui/react';\n\n<Card style={{ padding: 24 }}>\n  <Badge variant="success">灵感进行时</Badge>\n  <h3>下一个好点子</h3>\n  <p>从这里开始，把想法慢慢变成现实。</p>\n</Card>`,
    props: [["children / className / style / ref", "原生 div 属性", "—"]],
  },
  {
    name: "FilterBar",
    chinese: "筛选栏",
    category: "business",
    description: "少一点寻找，快一点到达想要的结果。",
    code: `import { useState } from 'react';\nimport { FilterBar } from '@ray-ui/react';\n\nexport function Filters() {\n  const [value, setValue] = useState('all');\n  return <FilterBar value={value} onValueChange={setValue}\n    options={[\n      { label: '全部', value: 'all', count: 12 },\n      { label: '进行中', value: 'active', count: 5 },\n      { label: '已完成', value: 'done', count: 7 },\n    ]} />;\n}`,
    props: [
      ["options", "{ label, value, count? }[]", "必填"],
      ["value / onValueChange", "string / (value: string) => void", "必填"],
      ["aria-label", "string", "筛选条件"],
    ],
  },
  {
    name: "Reveal",
    chinese: "入场动画",
    category: "motion",
    description: "随滚动轻轻出现，让浏览多一点节奏。",
    code: `import { Reveal } from '@ray-ui/react';\n\n<Reveal delay={100}>\n  <h3>你好，新的灵感。</h3>\n</Reveal>\n<Reveal delay={200} once={false}>\n  <p>进入视口时轻轻出现。</p>\n</Reveal>`,
    props: [
      ["delay", "number，单位 ms", "0"],
      ["once", "boolean", "true"],
      ["children / className / style / ref", "原生 div 属性", "—"],
    ],
  },
  {
    name: "Textarea",
    chinese: "文本域",
    category: "ui",
    description: "为长一点的想法，留出更多表达空间。",
    code: `import { Textarea } from '@ray-ui/react';\n\n<Textarea label="项目介绍" rows={3}\n  placeholder="写下你的想法…"\n  hint="描述一下你想打造的作品。" />`,
    props: [
      ["label / hint / error", "string", "—"],
      ["rows / value / onChange / ref", "原生 textarea 属性", "—"],
    ],
  },
  {
    name: "Separator",
    chinese: "分隔线",
    category: "ui",
    description: "一点留白，一条细线，让内容呼吸。",
    code: `import { Separator } from '@ray-ui/react';\n\n<div>账户设置</div>\n<Separator style={{ margin: '16px 0' }} />\n<div>通知偏好</div>`,
    props: [["className / style / ref", "原生 div 属性", "—"]],
  },
  {
    name: "CommandPalette",
    chinese: "命令面板",
    category: "ui",
    description: "把常用动作集中到一个可搜索、可键盘导航的小空间。",
    code: `import { CommandPalette } from '@ray-ui/react';

<CommandPalette
  open={open}
  onOpenChange={setOpen}
  onSelect={(item) => runCommand(item.id)}
  groups={[{
    heading: '快速开始',
    items: [{ id: 'new', label: '创建新项目', shortcut: ['⌘', 'N'] }],
  }]}
/>`,
    props: [
      ["groups", "CommandGroup[]；每组包含 heading? 与唯一 id 的 items", "必填"],
      ["open / defaultOpen / onOpenChange", "受控 / 初始打开状态 / 打开状态回调", "false / —"],
      ["value / defaultValue / onValueChange", "搜索词的受控 / 初始值与变化回调", "— / 空字符串"],
      ["onSelect / closeOnSelect", "选中项回调 / 执行后是否关闭面板", "— / true"],
      ["hotkey", "⌘ / Ctrl 加此按键时打开或关闭；传字符串启用，false 不注册全局快捷键", "false"],
      ["placeholder / emptyMessage / title / description", "搜索提示、无结果状态和对话框语义文案", "内置中文"],
      ["键盘与语义", "searchbox + listbox；方向键、Home / End、Enter、Escape；⌘ / Ctrl + K 关闭", "—"],
    ],
  },
  {
    name: "MetricCard",
    chinese: "指标卡",
    category: "business",
    description: "用一个数字、一条趋势和一小段上下文，讲清当前状态。",
    code: `import { MetricCard } from '@ray-ui/react';

<MetricCard
  label="本周灵感"
  value="1,280"
  delta="+18.4%"
  trend="up"
  trendLabel="较上周"
  data={[22, 30, 27, 42, 38, 52, 61]}
/>`,
    props: [
      ["label / value", "指标名称 / 主数值；value 支持 ReactNode", "必填"],
      ["delta / trend / trendLabel", "变化值、up | down | neutral 趋势和辅助说明", "— / neutral / —"],
      ["data", "readonly number[]；有限值会绘制为装饰性迷你折线，少于 2 个点时隐藏", "—"],
      ["icon / footer", "右上角图标 / 底部辅助内容", "—"],
      ["tone / loading", "default | accent | sage | amber / 骨架加载状态", "default / false"],
      ["className / style / ref", "原生 article 属性与 HTMLArticleElement ref", "—"],
    ],
  },
  {
    name: "SplitButton",
    chinese: "分裂按钮",
    category: "ui",
    description: "保留一个最常用的主操作，也把相关动作收进同一处菜单。",
    code: `import { SplitButton } from '@ray-ui/react';

<SplitButton
  onClick={() => exportFile('png')}
  actions={[
    { id: 'png', label: '导出 PNG', onSelect: () => exportFile('png') },
    { id: 'copy', label: '复制链接', onSelect: copyLink },
  ]}
>
  导出作品
</SplitButton>`,
    props: [
      ["children / onClick", "主按钮内容 / 主操作回调", "必填 / —"],
      ["actions", "SplitButtonAction[]；id 唯一，可带 icon、disabled、onSelect", "必填"],
      ["onAction", "菜单项选中后的统一回调，接收 action", "—"],
      ["open / defaultOpen / onOpenChange", "菜单的受控 / 初始打开状态与变化回调", "false / —"],
      ["variant / size", "primary | secondary | outline / sm | md | lg", "primary / md"],
      ["键盘与语义", "主按钮 + aria-haspopup=menu；菜单支持方向键、Home / End、Enter、Escape 和点击外部关闭", "—"],
    ],
  },
];
