export type Category = "all" | "ui" | "motion" | "business";
export interface ComponentDoc {
  name: string;
  chinese: string;
  category: Exclude<Category, "all">;
  description: string;
  code: string;
  props: [string, string, string][];
}

export const categories = [
  { value: "all", label: "全部组件" },
  { value: "ui", label: "通用 UI" },
  { value: "motion", label: "视觉动效" },
  { value: "business", label: "业务组件" },
] as const;

export const catalog: ComponentDoc[] = [
  {
    name: "BreathingIndicator",
    chinese: "呼吸指示器",
    category: "motion",
    description: "浮光、游环、潮息，让状态自然流动。",
    code: `import { BreathingIndicator } from '@ray-ui/react';\n\n<BreathingIndicator variant="glow" label="系统运行中" />\n<BreathingIndicator variant="orbit" label="正在同步" />\n<BreathingIndicator variant="wave" label="后台处理中" />`,
    props: [
      ["label / hideLabel", "string / boolean，状态文本 / 仅视觉隐藏文字，保留无障碍文本", "运行中 / false"],
      ["variant", "glow 浮光 | orbit 游环 | wave 潮息", "glow"],
      ["status", "normal 正常 | degraded 部分出错（琥珀色、变速） | failed 完全瘫痪（红色、静止）", "normal"],
      ["description", "string，可选说明文字", "—"],
      ["tone", "green | blue | orange | purple", "green"],
      ["size", "sm | md | lg", "md"],
      ["duration", "number，基础节奏毫秒，各层错速运动；最小 1600", "6000"],
      ["paused", "boolean，冻结当前动画，恢复时继续；不改变 label", "false"],
      ["className / style / ref", "原生 span 属性；尊重系统减少动态效果偏好", "—"],
    ],
  },
  {
    name: "DownloadButton",
    chinese: "下载按钮",
    category: "ui",
    description: "轻轻一点，把需要的文件带走。",
    code: `import { DownloadButton } from '@ray-ui/react';\n\n<DownloadButton filename="notes.txt" data="我的灵感笔记">\n  下载文件\n</DownloadButton>\n\n<DownloadButton filename="guide.pdf" href="/files/guide.pdf">\n  下载指南\n</DownloadButton>`,
    props: [
      ["filename", "string，建议保存的文件名", "必填"],
      ["data / href", "string | Blob 文件内容 / 文件 URL，二选一；跨域 URL 是否下载取决于服务端响应", "必填"],
      ["mimeType", "string，仅用于字符串 data", "text/plain;charset=utf-8"],
      ["icon / children", "ReactNode，图标 / 按钮文案", "— / 下载文件"],
      ["onDownload / onError", "请求下载后回调（不代表保存完成） / 错误回调", "—"],
      ["variant / size / disabled / loading / ref", "继承 Button 属性；onClick 可 preventDefault 取消下载", "同 Button"],
    ],
  },
  {
    name: "Leaderboard",
    chinese: "排行榜",
    category: "business",
    description: "四色进度条，让名次与成绩差距一眼清晰。",
    code: `import { Leaderboard } from '@ray-ui/react';\n\n<Leaderboard items={[\n  { id: 'lin', name: '林予安', value: 12860, tone: 'orange', change: 3 },\n  { id: 'chen', name: '陈墨', value: 11420, tone: 'blue', change: 1 },\n  { id: 'xu', name: '许知远', value: 10980, tone: 'purple', change: -1 },\n  { id: 'zhou', name: '周可', value: 9640, tone: 'teal', change: 0 },\n]} />`,
    props: [
      ["items", "LeaderboardItem[]，唯一 id、name、value；按分数降序展示", "必填"],
      ["items[].avatar / tone", "头像 URL / orange | blue | purple | teal", "姓名首字 / 按输入顺序轮换"],
      ["items[].change", "排名变化：正数上升、负数下降、0 持平", "0"],
      ["title / valueLabel", "标题 / 分数的可访问单位", "积分排行榜 / 积分"],
      ["formatValue", "(value: number) => string", "中文千位分隔"],
      ["renderChange", "(change: number) => ReactNode，自定义变化图标", "升 / 降 / 持平文字"],
      ["emptyMessage", "空状态文案", "暂无排行数据"],
      ["className / style", "外层 section 样式；百分比相对榜首，同分保持输入顺序", "—"],
    ],
  },
  {
    name: "ScrollArea",
    chinese: "滚动条",
    category: "ui",
    description: "细细一条，让长内容自在向下延伸。",
    code: `import { ScrollArea } from '@ray-ui/react';\n\n<ScrollArea aria-label="内容列表" style={{ height: 300 }}>\n  {/* 放入超过容器高度的内容，即可滚动 */}\n</ScrollArea>\n\n// 页面或已有滚动容器也可直接添加 className="ray-scrollbar"。`,
    props: [
      ["aria-label", "string，滚动区域的可访问名称", "必填"],
      ["children", "ReactNode，滚动内容", "—"],
      ["style / className", "容器样式，可设置 height / maxHeight", "max-height: 320px"],
      ["tabIndex / ref", "原生 div 属性；聚焦后支持键盘滚动", "0 / —"],
    ],
  },
  {
    name: "Slider",
    chinese: "滑动条",
    category: "ui",
    description: "轻轻滑动，把数值调到刚刚好。",
    code: `import { useState } from 'react';\nimport { Slider } from '@ray-ui/react';\n\nexport function Volume() {\n  const [value, setValue] = useState(64);\n  return <Slider label="播放音量" value={value}\n    onValueChange={setValue}\n    formatValue={(value) => value + '%'} />;\n}`,
    props: [
      ["label / value", "string / number，标签与受控数值", "必填"],
      ["onValueChange", "(value: number) => void", "—"],
      ["min / max / step", "number，范围与步长；value 应对齐步长", "0 / 100 / 1"],
      ["formatValue", "(value: number) => string，数值显示格式", "String"],
      ["disabled / name / ref", "原生 input 属性", "—"],
      ["className / style", "外层容器样式", "—"],
    ],
  },
  {
    name: "Button",
    chinese: "按钮",
    category: "ui",
    description: "每一次行动，都从一个清晰的按钮开始。",
    code: `import { Button } from '@ray-ui/react';\n\n<Button onClick={() => alert('开始构建！')}>\n  开始构建\n</Button>\n<Button variant="outline">了解更多</Button>\n<Button loading>正在保存</Button>`,
    props: [
      ["variant", "primary | secondary | outline | ghost | danger", "primary"],
      ["size", "sm | md | lg", "md"],
      ["loading", "boolean", "false"],
      ["disabled / onClick / ref", "原生 button 属性", "—"],
    ],
  },
  {
    name: "Input",
    chinese: "输入框",
    category: "ui",
    description: "标签、提示、校验反馈，照顾每一个输入。",
    code: `import { Input } from '@ray-ui/react';\n\n<Input label="邮箱地址" type="email"\n  placeholder="you@example.com"\n  hint="我们会好好保管你的邮箱。" />\n<Input label="项目名称" error="请填写项目名称" />`,
    props: [
      ["label", "string", "—"],
      ["hint / error", "string", "—"],
      ["value / onChange / ref", "原生 input 属性", "—"],
    ],
  },
  {
    name: "DatePicker",
    chinese: "日期选择器",
    category: "ui",
    description: "给下一次出发，选一个刚刚好的日子。",
    code: `import { useState } from 'react';\nimport { DatePicker } from '@ray-ui/react';\n\nexport function ProjectDate() {\n  const [date, setDate] = useState<Date | undefined>();\n  return (\n    <DatePicker\n      label="项目启动日期"\n      name="startDate"\n      value={date}\n      onValueChange={setDate}\n      minDate={new Date(2026, 8, 1)}\n      maxDate={new Date(2026, 11, 31)}\n      hint="请选择 2026 年 9–12 月的日期。"\n    />\n  );\n}`,
    props: [
      ["value / defaultValue", "Date | undefined，受控值 / 非受控初值", "—"],
      ["onValueChange", "(date: Date | undefined) => void，清除时传 undefined", "—"],
      ["minDate / maxDate", "Date，按本地日限制，含边界、忽略时分秒", "—"],
      ["label / placeholder", "string，标签 / 未选择时的提示", "— / 选择日期"],
      ["hint / error", "string，提示或错误信息", "—"],
      ["clearable / disabled", "boolean，允许清除 / 禁用整个控件", "true / false"],
      ["name", "string，表单提交为本地 YYYY-MM-DD", "—"],
      ["id / className / ref", "string / string / Ref<HTMLButtonElement>", "—"],
    ],
  },
  {
    name: "Switch",
    chinese: "开关",
    category: "ui",
    description: "一个小小的切换，让偏好即刻生效。",
    code: `import { useState } from 'react';\nimport { Switch } from '@ray-ui/react';\n\nexport function Preferences() {\n  const [enabled, setEnabled] = useState(true);\n  return <Switch label="接收更新通知"\n    checked={enabled} onCheckedChange={setEnabled} />;\n}`,
    props: [
      ["checked / defaultChecked", "boolean", "false"],
      ["onCheckedChange", "(checked: boolean) => void", "—"],
      ["label / disabled / name", "标签与原生 input 属性", "—"],
    ],
  },
  {
    name: "SpotlightCard",
    chinese: "聚光卡片",
    category: "motion",
    description: "光随指尖而动，为内容添一点灵感。",
    code: `import { SpotlightCard } from '@ray-ui/react';\n\n<SpotlightCard style={{ padding: 32 }}>\n  <h3>让灵感发光。</h3>\n  <p>移动指针，探索属于你的光。</p>\n</SpotlightCard>`,
    props: [
      ["children", "ReactNode", "—"],
      ["className / style / ref", "原生 div 属性", "—"],
    ],
  },
  {
    name: "Badge",
    chinese: "徽标",
    category: "ui",
    description: "轻巧的状态表达，让信息一目了然。",
    code: `import { Badge } from '@ray-ui/react';\n\n<Badge variant="success">已完成</Badge>\n<Badge variant="warning">进行中</Badge>\n<Badge variant="info">新功能</Badge>`,
    props: [
      ["variant", "neutral | success | warning | danger | info", "neutral"],
      ["children / className / ref", "原生 span 属性", "—"],
    ],
  },
  {
    name: "AnimatedNumber",
    chinese: "数字动画",
    category: "motion",
    description: "让每一份增长，都有恰到好处的仪式感。",
    code: `import { useState } from 'react';\nimport { AnimatedNumber, Button } from '@ray-ui/react';\n\nexport function Counter() {\n  const [value, setValue] = useState(1280);\n  return <>\n    <AnimatedNumber value={value} prefix="¥" duration={900} />\n    <Button onClick={() => setValue(value + 100)}>增加</Button>\n  </>;\n}`,
    props: [
      ["value", "number", "必填"],
      ["duration", "number，单位 ms", "900"],
      ["prefix / suffix / className", "string", "—"],
    ],
  },
  {
    name: "Tabs",
    chinese: "标签页",
    category: "ui",
    description: "切换视角，让相关内容井然有序。",
    code: `import { Tabs } from '@ray-ui/react';\n\n<Tabs aria-label="项目视图" items={[\n  { value: 'overview', label: '概览', content: <p>项目概览</p> },\n  { value: 'activity', label: '动态', content: <p>最近动态</p> },\n]} />`,
    props: [
      ["items", "{ value, label, content, disabled? }[]", "必填"],
      ["value / defaultValue", "string", "首个可用项"],
      ["onValueChange", "(value: string) => void", "—"],
    ],
  },
  {
    name: "Dialog",
    chinese: "对话框",
    category: "ui",
    description: "留一点专注空间，完成重要的事情。",
    code: `import { Dialog, Button, Input } from '@ray-ui/react';\n\n<Dialog trigger={<Button>创建项目</Button>}\n  title="创建新项目" description="给你的下一个想法起个名字。">\n  <Input label="项目名称" placeholder="我的新项目" />\n</Dialog>`,
    props: [
      ["trigger", "可接收 ref 与事件的元素，或文本", "必填"],
      ["title / description", "string", "标题必填"],
      ["open / onOpenChange", "boolean / (open: boolean) => void", "非受控"],
      ["children / className", "ReactNode / string", "—"],
    ],
  },
  {
    name: "StackedDrawer",
    chinese: "堆叠卡片抽屉",
    category: "ui",
    description: "新内容层层展开，来时的线索始终都在。",
    code: `import { StackedDrawer, Button, Input } from '@ray-ui/react';\n\n<StackedDrawer\n  trigger={<Button>打开项目</Button>}\n  title="项目概览" description="从一个小小的想法开始。"\n>\n  <Input label="项目名称" defaultValue="下一个好点子" />\n  <StackedDrawer\n    trigger={<Button>设计细节</Button>}\n    title="设计细节" description="上一张卡片会缩小后退。"\n  >\n    <p>关闭当前层后，上一层的输入依然保留。</p>\n    <StackedDrawer trigger={<Button>准备清单</Button>} title="准备清单">\n      <p>一切就绪，可以出发。</p>\n    </StackedDrawer>\n  </StackedDrawer>\n</StackedDrawer>`,
    props: [
      ["trigger", "可接收 ref 与事件的元素，或文本", "必填"],
      ["title / description", "string，当前卡片的标题与说明", "标题必填"],
      ["children", "ReactNode，可嵌套 StackedDrawer 形成多层卡片", "必填"],
      ["footer", "ReactNode，固定在底部的操作区", "—"],
      ["open / onOpenChange", "boolean / (open: boolean) => void", "非受控"],
      ["defaultOpen", "boolean，非受控模式下的初始状态", "false"],
      ["className", "string，卡片容器的自定义类名", "—"],
    ],
  },
  {
    name: "DataTable",
    chinese: "数据表格",
    category: "business",
    description: "搜索、排序与分页，把复杂数据变清晰。",
    code: `import { DataTable } from '@ray-ui/react';\n\nconst data = [\n  { id: '1', name: '设计系统', status: '进行中' },\n  { id: '2', name: '个人主页', status: '已完成' },\n];\n\n<DataTable data={data} caption="我的项目" pageSize={5}\n  columns={[\n    { key: 'name', header: '项目', sortable: true },\n    { key: 'status', header: '状态' },\n  ]} />`,
    props: [
      ["data", "T[]，每行必须有唯一 id: string", "必填"],
      ["columns", "{ key, header, sortable?, render? }[]", "必填"],
      ["pageSize", "number", "5"],
      ["caption / searchPlaceholder", "string", "数据列表 / 搜索数据…"],
    ],
  },
  {
    name: "StackedCards",
    chinese: "堆叠卡片列表",
    category: "ui",
    description: "把列表叠成一组卡片，点开一项，轻轻收好其余。",
    code: `import { StackedCards } from '@ray-ui/react';\n\n<StackedCards\n  aria-label="我的计划"\n  defaultValue="weekend"\n  items={[\n    { id: 'design', title: '品牌视觉探索', tone: 'sage',\n      meta: '09.10', content: <p>收集配色和字形灵感。</p> },\n    { id: 'room', title: '个人空间改造', tone: 'sand',\n      meta: '09.11', content: <p>一盏灯、一盆绿植。</p> },\n    { id: 'weekend', title: '周末漫游计划', tone: 'clay',\n      meta: '09.12', content: <p>带上相机，去收集一点日常之外。</p> },\n  ]}\n/>`,
    props: [
      ["items", "StackedCardItem[]，每项提供唯一 id、title、content", "必填"],
      ["items[].tone", "neutral | sage | sand | clay，卡片底色", "neutral"],
      ["items[].icon / meta", "ReactNode，标题图标 / 辅助信息，避免交互元素", "序号 / —"],
      ["value / defaultValue", "string | null，展开项 id；null 收起全部", "首项"],
      ["onValueChange", "(id: string | null) => void", "—"],
      ["className / aria-label", "自定义类名 / 列表的可访问名称", "— / 堆叠卡片列表"],
    ],
  },
  {
    name: "Card",
    chinese: "卡片",
    category: "ui",
    description: "给每一组内容，一个舒服的容器。",
    code: `import { Card, Badge } from '@ray-ui/react';\n\n<Card style={{ padding: 24 }}>\n  <Badge variant="success">灵感进行时</Badge>\n  <h3>下一个好点子</h3>\n  <p>从这里开始，把想法慢慢变成现实。</p>\n</Card>`,
    props: [["children / className / style / ref", "原生 div 属性", "—"]],
  },
  {
    name: "FilterBar",
    chinese: "筛选栏",
    category: "business",
    description: "少一点寻找，快一点到达想要的结果。",
    code: `import { useState } from 'react';\nimport { FilterBar } from '@ray-ui/react';\n\nexport function Filters() {\n  const [value, setValue] = useState('all');\n  return <FilterBar value={value} onValueChange={setValue}\n    options={[\n      { label: '全部', value: 'all', count: 12 },\n      { label: '进行中', value: 'active', count: 5 },\n      { label: '已完成', value: 'done', count: 7 },\n    ]} />;\n}`,
    props: [
      ["options", "{ label, value, count? }[]", "必填"],
      ["value / onValueChange", "string / (value: string) => void", "必填"],
      ["aria-label", "string", "筛选条件"],
    ],
  },
  {
    name: "Reveal",
    chinese: "入场动画",
    category: "motion",
    description: "随滚动轻轻出现，让浏览多一点节奏。",
    code: `import { Reveal } from '@ray-ui/react';\n\n<Reveal delay={100}>\n  <h3>你好，新的灵感。</h3>\n</Reveal>\n<Reveal delay={200} once={false}>\n  <p>进入视口时轻轻出现。</p>\n</Reveal>`,
    props: [
      ["delay", "number，单位 ms", "0"],
      ["once", "boolean", "true"],
      ["children / className / style / ref", "原生 div 属性", "—"],
    ],
  },
  {
    name: "Textarea",
    chinese: "文本域",
    category: "ui",
    description: "为长一点的想法，留出更多表达空间。",
    code: `import { Textarea } from '@ray-ui/react';\n\n<Textarea label="项目介绍" rows={3}\n  placeholder="写下你的想法…"\n  hint="描述一下你想打造的作品。" />`,
    props: [
      ["label / hint / error", "string", "—"],
      ["rows / value / onChange / ref", "原生 textarea 属性", "—"],
    ],
  },
  {
    name: "Separator",
    chinese: "分隔线",
    category: "ui",
    description: "一点留白，一条细线，让内容呼吸。",
    code: `import { Separator } from '@ray-ui/react';\n\n<div>账户设置</div>\n<Separator style={{ margin: '16px 0' }} />\n<div>通知偏好</div>`,
    props: [["className / style / ref", "原生 div 属性", "—"]],
  },
];
